package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/reglyph/g8n/internal/parser"
)

const goSchema = "# @package=config\n# @out(path=env.go)\nDB_HOST=localhost\n"
const tsSchema = "# @out(path=env.ts)\nDB_HOST=localhost\n"

func writeFile(t *testing.T, dir, name, content string) string {
	t.Helper()

	path := filepath.Join(dir, name)

	// #nosec G301 -- test fixtures use the account's default umask
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}

	return path
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	// #nosec G304 -- reading back files written by the test itself
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	return string(data)
}

func runWith(t *testing.T, args ...string) (code int, stdout, stderr string) {
	t.Helper()

	var out, errBuf bytes.Buffer

	code = run(args, &out, &errBuf)

	return code, out.String(), errBuf.String()
}

func TestBasePackageName(t *testing.T) {
	cases := []struct {
		name string
		out  string
		want string
	}{
		{"defaults to env for empty dir", "env.go", "env"},
		{"derives from directory", "internal/config/env.go", "config"},
		{"strips hyphens", "work/api-key/env.go", "apikey"},
		{"prefixes leading digit", "out/2fa/env.go", "env_2fa"},
		{"strips dots", "out/my.dir/env.go", "mydir"},
		{"root directory", "/env.go", "env"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, err := basePackageName(tc.out)
			if err != nil {
				t.Fatalf("basePackageName(%q): %v", tc.out, err)
			}

			if got != tc.want {
				t.Errorf("basePackageName(%q) = %q, want %q", tc.out, got, tc.want)
			}
		})
	}
}

func TestBasePackageNameRejectsKeywords(t *testing.T) {
	for _, kw := range []string{"type", "func", "range", "select"} {
		_, err := basePackageName("work/" + kw + "/env.go")
		if err == nil {
			t.Errorf("basePackageName(work/%s/env.go): expected error for Go keyword", kw)
		}
	}
}

func TestRunVersion(t *testing.T) {
	code, stdout, _ := runWith(t, "-version")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	if !strings.Contains(stdout, "@reglyph/g8n") {
		t.Errorf("stdout = %q, want version banner", stdout)
	}
}

func TestRunHelpExitCodeZero(t *testing.T) {
	code, _, _ := runWith(t, "-help")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0 for -help", code)
	}
}

func TestRunUnknownFlagExitCodeTwo(t *testing.T) {
	code, _, stderr := runWith(t, "-nope")
	if code != 2 {
		t.Fatalf("exit code = %d, want 2 for unknown flag", code)
	}

	if !strings.Contains(stderr, "flag provided but not defined") {
		t.Errorf("stderr = %q, want unknown flag message", stderr)
	}
}

func TestRunPositionalArgsExitCodeTwo(t *testing.T) {
	code, _, stderr := runWith(t, "extra")
	if code != 2 {
		t.Fatalf("exit code = %d, want 2 for positional args", code)
	}

	if !strings.Contains(stderr, "unexpected positional arguments") {
		t.Errorf("stderr = %q, want positional args message", stderr)
	}
}

func TestRunMissingBaseSchema(t *testing.T) {
	code, _, stderr := runWith(t, "-schema", filepath.Join(t.TempDir(), "nope.env"))
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}

	if !strings.Contains(stderr, "nope.env") {
		t.Errorf("stderr = %q, want missing schema path", stderr)
	}
}

func TestRunGenerateSuccess(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)
	out := filepath.Join(dir, "generated", "env.go")

	code, _, stderr := runWith(t, "-schema", schema, "-out", out)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0; stderr: %s", code, stderr)
	}

	src := readFile(t, out)

	if !strings.HasPrefix(string(src), "// Code generated by g8n. DO NOT EDIT.") {
		t.Errorf("output missing generated header")
	}

	if !strings.Contains(string(src), "package config") {
		t.Errorf("output missing package config")
	}

	if !strings.Contains(string(src), `m["DB_HOST"]`) {
		t.Errorf("output missing DB_HOST field")
	}
}

func TestRunOutFlagWinsOverDecorator(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)
	flagOut := filepath.Join(dir, "from-flag.go")

	code, _, _ := runWith(t, "-schema", schema, "-out", flagOut)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	if _, err := os.Stat(flagOut); err != nil {
		t.Errorf("-out flag file not written: %v", err)
	}

	if _, err := os.Stat(filepath.Join(dir, "env.go")); !os.IsNotExist(err) {
		t.Errorf("@out(path=env.go) must be ignored when -out is passed")
	}
}

func TestRunPackageFlag(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)

	code, stdout, _ := runWith(t, "-schema", schema, "-out", filepath.Join(dir, "env.go"), "-package", "custom", "-dry-run")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	if !strings.Contains(stdout, "package custom") {
		t.Errorf("stdout missing package custom")
	}
}

func TestRunDryRunDoesNotWrite(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)
	out := filepath.Join(dir, "env.go")

	code, stdout, _ := runWith(t, "-schema", schema, "-out", out, "-dry-run")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	if !strings.Contains(stdout, "package config") {
		t.Errorf("dry-run must print source to stdout")
	}

	if _, err := os.Stat(out); !os.IsNotExist(err) {
		t.Errorf("-dry-run must not write %s", out)
	}
}

func TestRunForceRewrite(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)
	out := filepath.Join(dir, "env.go")

	if _, _, stderr := runWith(t, "-schema", schema, "-out", out); !strings.Contains(stderr, "wrote") {
		t.Fatalf("first run stderr = %q, want wrote", stderr)
	}

	if _, _, stderr := runWith(t, "-schema", schema, "-out", out); !strings.Contains(stderr, "up to date") {
		t.Errorf("second run stderr = %q, want up to date", stderr)
	}

	if _, _, stderr := runWith(t, "-schema", schema, "-out", out, "-force"); !strings.Contains(stderr, "refreshed") {
		t.Errorf("-force run stderr = %q, want refreshed", stderr)
	}
}

func TestRunJSONSchema(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)
	jsonPath := filepath.Join(dir, "schema.json")

	code, _, _ := runWith(t, "-schema", schema, "-json", jsonPath)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	src := readFile(t, jsonPath)

	if !strings.Contains(string(src), `"$schema"`) || !strings.Contains(string(src), "DB_HOST") {
		t.Errorf("JSON schema output missing $schema or DB_HOST")
	}
}

func TestRunJSONSchemaDryRun(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)
	jsonPath := filepath.Join(dir, "schema.json")

	code, stdout, _ := runWith(t, "-schema", schema, "-json", jsonPath, "-dry-run")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	if !strings.Contains(stdout, `"$schema"`) {
		t.Errorf("-dry-run must print JSON schema to stdout")
	}

	if _, err := os.Stat(jsonPath); !os.IsNotExist(err) {
		t.Errorf("-dry-run must not write %s", jsonPath)
	}
}

func TestRunEnvOverlay(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", "# @package=config\n# @out(path=env.go)\nDB_HOST=base\n")

	out := filepath.Join(dir, "env.go")

	writeFile(t, dir, ".env.local", "DB_HOST=local\n")
	writeFile(t, dir, ".env.prod", "DB_HOST=prod\nNEW_KEY=added\n")

	code, _, _ := runWith(t, "-schema", schema)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	src := readFile(t, out)

	if !strings.Contains(string(src), `"local"`) {
		t.Errorf("default overlay .env.local not applied, got:\n%s", src)
	}

	code, _, _ = runWith(t, "-schema", schema, "-env", "prod", "-force")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	src = readFile(t, out)

	if !strings.Contains(string(src), `"prod"`) {
		t.Errorf("-env prod overlay not applied, got:\n%s", src)
	}

	if !strings.Contains(string(src), `m["NEW_KEY"]`) {
		t.Errorf("-env prod overlay did not add NEW_KEY, got:\n%s", src)
	}
}

func TestRunDefaultSchemaWithoutFlags(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir, ".env.schema", goSchema)

	old, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}

	if err := os.Chdir(dir); err != nil {
		t.Fatal(err)
	}

	defer func() {
		_ = os.Chdir(old)
	}()

	code, _, _ := runWith(t)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0 with default flags", code)
	}

	if _, err := os.Stat(filepath.Join(dir, "env.go")); err != nil {
		t.Errorf("default @out(path=env.go) not resolved, got %v", err)
	}
}

func TestRunGenerateTS(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", tsSchema)
	out := filepath.Join(dir, "env.ts")

	code, _, stderr := runWith(t, "-schema", schema, "-lang", "ts", "-out", out)
	if code != 0 {
		t.Fatalf("exit code = %d, want 0; stderr: %s", code, stderr)
	}

	if !strings.Contains(stderr, "experimental and may change") {
		t.Errorf("stderr = %q, want experimental warning", stderr)
	}

	src := readFile(t, out)

	if !strings.HasPrefix(string(src), "// Code generated by g8n. DO NOT EDIT.") {
		t.Errorf("output missing generated header")
	}

	if !strings.Contains(string(src), "export interface Env") {
		t.Errorf("output missing Env interface")
	}
}

func TestRunGenerateTSDryRun(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", tsSchema)
	out := filepath.Join(dir, "env.ts")

	code, stdout, _ := runWith(t, "-schema", schema, "-lang", "ts", "-out", out, "-dry-run")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0", code)
	}

	if !strings.Contains(stdout, "export interface Env") {
		t.Errorf("dry-run must print TypeScript source to stdout")
	}

	if _, err := os.Stat(out); !os.IsNotExist(err) {
		t.Errorf("-dry-run must not write %s", out)
	}
}

func TestRunTSIgnoresPackage(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)
	out := filepath.Join(dir, "env.ts")

	code, _, stderr := runWith(t, "-schema", schema, "-lang", "ts", "-out", out, "-package", "custom")
	if code != 0 {
		t.Fatalf("exit code = %d, want 0; stderr: %s", code, stderr)
	}

	if !strings.Contains(stderr, "package name is ignored for TypeScript") {
		t.Errorf("stderr = %q, want TypeScript package warning", stderr)
	}
}

func TestRunUnsupportedLang(t *testing.T) {
	dir := t.TempDir()
	schema := writeFile(t, dir, "schema.env", goSchema)

	code, _, stderr := runWith(t, "-schema", schema, "-lang", "rust")
	if code != 1 {
		t.Fatalf("exit code = %d, want 1", code)
	}

	if !strings.Contains(stderr, `unsupported language "rust"`) {
		t.Errorf("stderr = %q, want unsupported language", stderr)
	}
}

func TestResolveOutputTS(t *testing.T) {
	dir := t.TempDir()
	schemaPath := filepath.Join(dir, "schema.env")

	schema := &parser.Schema{OutPath: "rel/env.ts"}

	if out, err := resolveOutputTS(schemaPath, schema, ""); err != nil || out != filepath.Join(dir, "rel/env.ts") {
		t.Errorf("@out not resolved: out = %q, err = %v", out, err)
	}

	if out, err := resolveOutputTS(schemaPath, schema, "abs.ts"); err != nil || out != "abs.ts" {
		t.Errorf("-out flag not kept: out = %q, err = %v", out, err)
	}

	if _, err := resolveOutputTS(schemaPath, &parser.Schema{}, ""); err == nil || !strings.Contains(err.Error(), "no out path") {
		t.Errorf("want no out path error, got %v", err)
	}
}

func TestResolveOutputs(t *testing.T) {
	dir := t.TempDir()
	schemaPath := filepath.Join(dir, "schema.env")

	schema := &parser.Schema{Package: "spkg", OutPath: "rel/env.go"}

	if pkg, out, err := resolveOutputs(schemaPath, schema, "fpkg", ""); err != nil || pkg != "fpkg" || out != filepath.Join(dir, "rel/env.go") {
		t.Errorf("flag package discarded: pkg = %q, out = %q, err = %v", pkg, out, err)
	}

	if pkg, out, err := resolveOutputs(schemaPath, schema, "", ""); err != nil || pkg != "spkg" || out != filepath.Join(dir, "rel/env.go") {
		t.Errorf("schema package/@out not used: pkg = %q, out = %q, err = %v", pkg, out, err)
	}

	noOut := &parser.Schema{}

	if _, _, err := resolveOutputs(schemaPath, noOut, "", ""); err == nil || !strings.Contains(err.Error(), "no out path") {
		t.Errorf("want no out path error, got %v", err)
	}

	if pkg, out, err := resolveOutputs(schemaPath, noOut, "", "my-dir/env.go"); err != nil || pkg != "mydir" || out != "my-dir/env.go" {
		t.Errorf("derived package = %q, out = %q, err = %v, want mydir", pkg, out, err)
	}
}

func TestResolveOutputsInvalidPackage(t *testing.T) {
	if _, _, err := resolveOutputs(t.TempDir(), &parser.Schema{}, "bad-name", "x.go"); err == nil || !strings.Contains(err.Error(), "invalid Go package name") {
		t.Errorf("want invalid package error, got %v", err)
	}
}

func TestWriteIfChanged(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "env.go")
	src := []byte("// code\n")

	var stderr bytes.Buffer

	if err := writeIfChanged(path, src, false, &stderr); err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(stderr.String(), "wrote") {
		t.Errorf("first write stderr = %q, want wrote", stderr.String())
	}

	stderr.Reset()

	if err := writeIfChanged(path, src, false, &stderr); err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(stderr.String(), "up to date") {
		t.Errorf("unchanged stderr = %q, want up to date", stderr.String())
	}

	got := readFile(t, path)

	if string(got) != string(src) {
		t.Errorf("unchanged run must not modify the file")
	}

	stderr.Reset()

	if err := writeIfChanged(path, src, true, &stderr); err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(stderr.String(), "refreshed") {
		t.Errorf("force stderr = %q, want refreshed", stderr.String())
	}

	stderr.Reset()

	if err := writeIfChanged(path, []byte("// new\n"), false, &stderr); err != nil {
		t.Fatal(err)
	}

	if !strings.Contains(stderr.String(), "wrote") {
		t.Errorf("changed stderr = %q, want wrote", stderr.String())
	}

	got = readFile(t, path)

	if string(got) != "// new\n" {
		t.Errorf("file not updated, got %q", got)
	}
}

func TestWriteIfChangedMkdir(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nested", "deep", "env.go")
	var stderr bytes.Buffer

	if err := writeIfChanged(path, []byte("// code\n"), false, &stderr); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(filepath.Dir(path)); err != nil {
		t.Errorf("parent directory not created: %v", err)
	}
}
