package typescript

import (
	"strconv"
	"strings"

	"github.com/reglyph/g8n/internal/naming"
	"github.com/reglyph/g8n/internal/parser"
	"github.com/reglyph/g8n/internal/printer"
	"github.com/reglyph/g8n/internal/spec"
)

func (g *tsGen) writeHeader(p *printer.Printer) {
	p.Line("// Code generated by g8n. DO NOT EDIT.")
	p.Blank()
	p.Line("declare const process: { env: Record<string, string | undefined> };")
	p.Blank()
}

func (g *tsGen) writeInterface(p *printer.Printer) {
	p.Line("export interface Env {")
	p.Indent()

	for _, f := range g.schema.Fields {
		if f.Sensitive {
			p.Linef("/** %s (sensitive) */", f.Key)
		} else {
			p.Linef("/** %s */", f.Key)
		}

		for _, doc := range f.Docs {
			if doc != "" {
				p.Linef("/** %s */", doc)
			}
		}

		opt := ""
		if !f.Required {
			opt = "?"
		}

		p.Linef("%s%s: %s;", g.fieldName(f.Key), opt, g.tsType(f))
		p.Blank()
	}

	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *tsGen) writeSensitiveKeys(p *printer.Printer) {
	p.Line("const sensitiveKeys = new Set<string>([")
	p.Indent()

	for _, f := range g.schema.Fields {
		if f.Sensitive {
			p.Linef("%s,", strconv.Quote(f.Key))
		}
	}

	p.Dedent()
	p.Line("]);")
	p.Blank()

	p.Line("export function SensitiveKeys(): Set<string> {")
	p.Indent()
	p.Line("return new Set(sensitiveKeys);")
	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *tsGen) writeLoaders(p *printer.Printer) error {
	p.Line("export function Load(): Env {")
	p.Indent()
	p.Line("return loadFromMap(process.env as Record<string, string | undefined>);")
	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("export function LoadFrom(")
	p.Indent()
	p.Line("environ: Record<string, string | undefined>,")
	p.Dedent()
	p.Line("): Env {")
	p.Indent()
	p.Line("return loadFromMap(environ);")
	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("function loadFromMap(m: Record<string, string | undefined>): Env {")
	p.Indent()
	p.Line("const e = {} as Env;")

	for _, f := range g.schema.Fields {
		if err := g.writeFieldLoad(p, f); err != nil {
			return err
		}
	}

	p.Line("return e;")
	p.Dedent()
	p.Line("}")
	p.Blank()

	return nil
}

func (g *tsGen) writeEnumHelper(p *printer.Printer) {
	if !g.hasEnum {
		return
	}

	for _, f := range g.schema.Fields {
		if f.Kind != spec.KindEnum {
			continue
		}

		quoted := make([]string, 0, len(f.Enum))

		for _, v := range f.Enum {
			quoted = append(quoted, strconv.Quote(v))
		}

		p.Linef("const %s = [%s] as const;", g.enumValuesName(f), strings.Join(quoted, ", "))
		p.Blank()
		p.Linef("export type %s = (typeof %s)[number];", g.enumTypeName(f), g.enumValuesName(f))
		p.Blank()
	}
}

func (g *tsGen) writeExpandHelper(p *printer.Printer) {
	if !g.hasExpand {
		return
	}

	p.WriteRaw(expandHelperSource)
	p.Blank()
}

func (g *tsGen) writeRegexVars(p *printer.Printer) {
	for _, f := range g.schema.Fields {
		if !f.HasRegex() {
			continue
		}

		p.Linef("const %s = new RegExp(%s);", g.regexVar(f), strconv.Quote(f.Regex))
		p.Blank()
	}
}

func (g *tsGen) writeConversionHelpers(p *printer.Printer) {
	if g.uses["int"] {
		p.WriteRaw(parseIntStrictSource)
		p.Blank()
	}

	if g.uses["bool"] {
		p.WriteRaw(parseBoolStrictSource)
		p.Blank()
	}

	if g.uses["float"] {
		p.WriteRaw(parseFloatStrictSource)
		p.Blank()
	}

	if g.uses["url"] {
		p.WriteRaw(isValidURLSource)
		p.Blank()
	}
}

// enumValuesName returns the `as const` array name for an enum field.
func (g *tsGen) enumValuesName(f *parser.Field) string {
	return g.fieldName(f.Key) + "Values"
}

// enumTypeName returns the union type name for an enum field.
func (g *tsGen) enumTypeName(f *parser.Field) string {
	return naming.UpperFirst(g.fieldName(f.Key))
}
