package golang

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/reglyph/g8n/internal/parser"
	"github.com/reglyph/g8n/internal/printer"
	"github.com/reglyph/g8n/internal/spec"
)

func (g *goGen) writeHeader(p *printer.Printer) error {
	if g.schema.Package == "" {
		return fmt.Errorf("package name is required")
	}

	p.Line("// Code generated by g8n. DO NOT EDIT.")
	p.Blank()
	p.Linef("package %s", g.schema.Package)
	p.Blank()

	return nil
}

func (g *goGen) writeImports(p *printer.Printer) {
	var paths []string
	if g.uses["context"] {
		paths = append(paths, "context")
	}

	if g.uses["net/url"] {
		paths = append(paths, "net/url")
	}

	if g.uses["strconv"] {
		paths = append(paths, "strconv")
	}

	if g.uses["fmt"] {
		paths = append(paths, "fmt")
	}

	if g.uses["os"] {
		paths = append(paths, "os")
	}

	if g.uses["os/exec"] {
		paths = append(paths, "os/exec")
	}

	if g.uses["regexp"] {
		paths = append(paths, "regexp")
	}

	if g.uses["strings"] {
		paths = append(paths, "strings")
	}

	if g.uses["time"] {
		paths = append(paths, "time")
	}

	if len(paths) == 0 {
		return
	}

	p.Line("import (")
	p.Indent()

	for _, path := range paths {
		p.Linef("%q", path)
	}

	p.Dedent()
	p.Line(")")
	p.Blank()
}

func (g *goGen) writeStruct(p *printer.Printer) {
	p.Line("type Env struct {")
	p.Indent()

	for _, f := range g.schema.Fields {
		g.writeStructField(p, f)
	}

	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *goGen) writeStructField(p *printer.Printer, f *parser.Field) {
	if f.Sensitive {
		p.Linef("// %s (sensitive)", f.Key)
	} else {
		p.Linef("// %s", f.Key)
	}

	for _, doc := range f.Docs {
		if doc != "" {
			p.Linef("// %s", doc)
		}
	}

	typ := f.Kind.Spec().GoType
	if !f.Required {
		typ = "*" + typ
	}

	p.Linef("%s %s `env:%q`", g.fieldName(f.Key), typ, f.Key)
	p.Blank()
}

func (g *goGen) writeSensitiveKeys(p *printer.Printer) {
	p.Line("var sensitiveKeys = map[string]struct{}{")
	p.Indent()

	for _, f := range g.schema.Fields {
		if f.Sensitive || len(f.SourceSpecs) > 0 {
			p.Linef("%q: {},", f.Key)
		}
	}

	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("func SensitiveKeys() map[string]struct{} {")
	p.Indent()
	p.Line("out := make(map[string]struct{}, len(sensitiveKeys))")
	p.Line("for k := range sensitiveKeys {")
	p.Indent()
	p.Line("out[k] = struct{}{}")
	p.Dedent()
	p.Line("}")
	p.Line("return out")
	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *goGen) writeLoaders(p *printer.Printer) error {
	p.Line("func Load() (Env, error) {")
	p.Indent()
	p.Line("return LoadFrom(os.Environ())")
	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("func LoadFrom(environ []string) (Env, error) {")
	p.Indent()
	p.Line("m := make(map[string]string, len(environ))")
	p.Line("for _, kv := range environ {")
	p.Indent()
	p.Line("if i := strings.IndexByte(kv, '='); i >= 0 {")
	p.Indent()
	p.Line("m[kv[:i]] = kv[i+1:]")
	p.Dedent()
	p.Line("}")
	p.Dedent()
	p.Line("}")

	if len(g.providers) > 0 {
		p.Line("if err := fetchAllSecrets(m); err != nil {")
		p.Indent()
		p.Line("var e Env")
		p.Line("return e, err")
		p.Dedent()
		p.Line("}")
	}

	p.Line("return loadFromMap(m)")
	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("func loadFromMap(m map[string]string) (Env, error) {")
	p.Indent()
	p.Line("var e Env")

	for _, f := range g.schema.Fields {
		if err := g.writeFieldLoad(p, f); err != nil {
			return err
		}
	}

	p.Line("return e, nil")
	p.Dedent()
	p.Line("}")
	p.Blank()

	return nil
}

func (g *goGen) writeEnumHelper(p *printer.Printer) {
	if !g.hasEnum {
		return
	}

	p.WriteRaw(enumHelperSource)
	p.Blank()
}

func (g *goGen) writeExpandHelper(p *printer.Printer) {
	if !g.hasExpand {
		return
	}

	p.WriteRaw(expandHelperSource)
	p.Blank()
}

func (g *goGen) writeRegexVars(p *printer.Printer) {
	for _, f := range g.schema.Fields {
		if !f.HasRegex() {
			continue
		}

		p.Linef("var %s = regexp.MustCompile(%q)", g.regexVar(f), f.Regex)
		p.Blank()
	}
}

func (g *goGen) writeSecretFetchers(p *printer.Printer) {
	if len(g.providers) == 0 {
		return
	}

	for _, pr := range providerOrder {
		if !g.providers[pr] {
			continue
		}

		if pr == spec.Provider1Password {
			p.WriteRaw(onePasswordFetcherSource)
			p.Blank()
		}
	}

	g.writeFetchAllSecrets(p)
}

func (g *goGen) writeFetchAllSecrets(p *printer.Printer) {
	p.Line("func fetchAllSecrets(m map[string]string) error {")
	p.Indent()

	for _, f := range g.schema.Fields {
		if len(f.SourceSpecs) > 0 {
			g.writeFetchBlock(p, f)
		}
	}

	p.Line("return nil")
	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *goGen) writeFetchBlock(p *printer.Printer, f *parser.Field) {
	key := strconv.Quote(f.Key)
	p.Linef("{ // %s", f.Key)
	p.Indent()

	first := &f.SourceSpecs[0]

	if !knownProvider(first.Provider) {
		g.writeUnsupportedProvider(p, f, first.Provider)
		return
	}

	p.Linef("v, err := %s", g.fetchCall(first))

	for sp := first.Next; sp != nil; sp = sp.Next {
		if !knownProvider(sp.Provider) {
			g.writeUnsupportedProvider(p, f, sp.Provider)
			return
		}

		p.Line("if err != nil {")
		p.Indent()
		p.Linef("v, err = %s", g.fetchCall(sp))
		p.Dedent()
		p.Line("}")
	}

	if f.Required {
		p.Line("if err != nil {")
		p.Indent()
		p.Linef("return fmt.Errorf(%q, err)", "fetch "+f.Key+": %w")
		p.Dedent()
		p.Line("}")
		p.Linef("m[%s] = v", key)
	} else {
		p.Line("if err == nil {")
		p.Indent()
		p.Linef("m[%s] = v", key)
		p.Dedent()
		p.Line("}")
	}

	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *goGen) fetchCall(sp *spec.SourceSpec) string {
	return fetcherFuncName(sp.Provider) + "(" + strings.Join(fetcherArgs(sp), ", ") + ")"
}

// writeUnsupportedProvider emits an immediate error for providers the generator does not know.
func (g *goGen) writeUnsupportedProvider(p *printer.Printer, f *parser.Field, pr spec.SecretProvider) {
	p.Linef("return fmt.Errorf(%q, %q)", "fetch "+f.Key+": unsupported secret provider %q", string(pr))
	p.Dedent()
	p.Line("}")
	p.Blank()
}

// knownProvider reports whether the generator can emit a fetcher for the provider.
func knownProvider(pr spec.SecretProvider) bool {
	_, ok := spec.ParseSecretProvider(string(pr))

	return ok
}
