package generator

import (
	"fmt"

	"github.com/reglyph/g8n/internal/parser"
)

func (g *gen) writeHeader(p *printer) error {
	if g.schema.Package == "" {
		return fmt.Errorf("package name is required")
	}

	p.line("// Code generated by g8n. DO NOT EDIT.")
	p.blank()
	p.linef("package %s", g.schema.Package)
	p.blank()

	return nil
}

func (g *gen) writeImports(p *printer) {
	var paths []string
	if g.uses["net/url"] {
		paths = append(paths, "net/url")
	}

	if g.uses["strconv"] {
		paths = append(paths, "strconv")
	}

	if g.uses["fmt"] {
		paths = append(paths, "fmt")
	}

	if g.uses["os"] {
		paths = append(paths, "os")
	}

	if g.uses["regexp"] {
		paths = append(paths, "regexp")
	}

	if g.uses["strings"] {
		paths = append(paths, "strings")
	}

	if len(paths) == 0 {
		return
	}

	p.line("import (")
	p.indent()

	for _, path := range paths {
		p.linef("%q", path)
	}

	p.dedent()
	p.line(")")
	p.blank()
}

func (g *gen) writeStruct(p *printer) {
	p.line("type Env struct {")
	p.indent()

	for _, f := range g.schema.Fields {
		g.writeStructField(p, f)
	}

	p.dedent()
	p.line("}")
	p.blank()
}

func (g *gen) writeStructField(p *printer, f *parser.Field) {
	if f.Sensitive {
		p.linef("// %s (sensitive)", f.Key)
	} else {
		p.linef("// %s", f.Key)
	}

	for _, doc := range f.Docs {
		if doc != "" {
			p.linef("// %s", doc)
		}
	}

	typ := f.Kind.Spec().GoType
	if !f.Required {
		typ = "*" + typ
	}

	p.linef("%s %s `env:%q`", g.fieldName(f.Key), typ, f.Key)
	p.blank()
}

func (g *gen) writeSensitiveKeys(p *printer) {
	p.line("var sensitiveKeys = map[string]struct{}{")
	p.indent()

	for _, f := range g.schema.Fields {
		if f.Sensitive {
			p.linef("%q: {},", f.Key)
		}
	}

	p.dedent()
	p.line("}")
	p.blank()

	p.line("func SensitiveKeys() map[string]struct{} {")
	p.indent()
	p.line("out := make(map[string]struct{}, len(sensitiveKeys))")
	p.line("for k := range sensitiveKeys {")
	p.indent()
	p.line("out[k] = struct{}{}")
	p.dedent()
	p.line("}")
	p.line("return out")
	p.dedent()
	p.line("}")
	p.blank()
}

func (g *gen) writeLoaders(p *printer) error {
	p.line("func Load() (Env, error) {")
	p.indent()
	p.line("return LoadFrom(os.Environ())")
	p.dedent()
	p.line("}")
	p.blank()

	p.line("func LoadFrom(environ []string) (Env, error) {")
	p.indent()
	p.line("m := make(map[string]string, len(environ))")
	p.line("for _, kv := range environ {")
	p.indent()
	p.line("if i := strings.IndexByte(kv, '='); i >= 0 {")
	p.indent()
	p.line("m[kv[:i]] = kv[i+1:]")
	p.dedent()
	p.line("}")
	p.dedent()
	p.line("}")
	p.line("return loadFromMap(m)")
	p.dedent()
	p.line("}")
	p.blank()

	p.line("func loadFromMap(m map[string]string) (Env, error) {")
	p.indent()
	p.line("var e Env")

	for _, f := range g.schema.Fields {
		if err := g.writeFieldLoad(p, f); err != nil {
			return err
		}
	}

	p.line("return e, nil")
	p.dedent()
	p.line("}")
	p.blank()

	return nil
}

func (g *gen) writeEnumHelper(p *printer) {
	if !g.hasEnum {
		return
	}

	p.writeRaw(enumHelperSource)
	p.blank()
}

func (g *gen) writeExpandHelper(p *printer) {
	if !g.hasExpand {
		return
	}

	p.writeRaw(expandHelperSource)
	p.blank()
}

func (g *gen) writeRegexVars(p *printer) {
	for _, f := range g.schema.Fields {
		if !f.HasRegex() {
			continue
		}

		p.linef("var %s = regexp.MustCompile(%q)", g.regexVar(f), f.Regex)
		p.blank()
	}
}
