package generator

import (
	"fmt"

	"github.com/reglyph/g8n/internal/parser"
	"github.com/reglyph/g8n/internal/printer"
)

func (g *gen) writeHeader(p *printer.Printer) error {
	if g.schema.Package == "" {
		return fmt.Errorf("package name is required")
	}

	p.Line("// Code generated by g8n. DO NOT EDIT.")
	p.Blank()
	p.Linef("package %s", g.schema.Package)
	p.Blank()

	return nil
}

func (g *gen) writeImports(p *printer.Printer) {
	var paths []string
	if g.uses["net/url"] {
		paths = append(paths, "net/url")
	}

	if g.uses["strconv"] {
		paths = append(paths, "strconv")
	}

	if g.uses["fmt"] {
		paths = append(paths, "fmt")
	}

	if g.uses["os"] {
		paths = append(paths, "os")
	}

	if g.uses["regexp"] {
		paths = append(paths, "regexp")
	}

	if g.uses["strings"] {
		paths = append(paths, "strings")
	}

	if len(paths) == 0 {
		return
	}

	p.Line("import (")
	p.Indent()

	for _, path := range paths {
		p.Linef("%q", path)
	}

	p.Dedent()
	p.Line(")")
	p.Blank()
}

func (g *gen) writeStruct(p *printer.Printer) {
	p.Line("type Env struct {")
	p.Indent()

	for _, f := range g.schema.Fields {
		g.writeStructField(p, f)
	}

	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *gen) writeStructField(p *printer.Printer, f *parser.Field) {
	if f.Sensitive {
		p.Linef("// %s (sensitive)", f.Key)
	} else {
		p.Linef("// %s", f.Key)
	}

	for _, doc := range f.Docs {
		if doc != "" {
			p.Linef("// %s", doc)
		}
	}

	typ := f.Kind.Spec().GoType
	if !f.Required {
		typ = "*" + typ
	}

	p.Linef("%s %s `env:%q`", g.fieldName(f.Key), typ, f.Key)
	p.Blank()
}

func (g *gen) writeSensitiveKeys(p *printer.Printer) {
	p.Line("var sensitiveKeys = map[string]struct{}{")
	p.Indent()

	for _, f := range g.schema.Fields {
		if f.Sensitive {
			p.Linef("%q: {},", f.Key)
		}
	}

	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("func SensitiveKeys() map[string]struct{} {")
	p.Indent()
	p.Line("out := make(map[string]struct{}, len(sensitiveKeys))")
	p.Line("for k := range sensitiveKeys {")
	p.Indent()
	p.Line("out[k] = struct{}{}")
	p.Dedent()
	p.Line("}")
	p.Line("return out")
	p.Dedent()
	p.Line("}")
	p.Blank()
}

func (g *gen) writeLoaders(p *printer.Printer) error {
	p.Line("func Load() (Env, error) {")
	p.Indent()
	p.Line("return LoadFrom(os.Environ())")
	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("func LoadFrom(environ []string) (Env, error) {")
	p.Indent()
	p.Line("m := make(map[string]string, len(environ))")
	p.Line("for _, kv := range environ {")
	p.Indent()
	p.Line("if i := strings.IndexByte(kv, '='); i >= 0 {")
	p.Indent()
	p.Line("m[kv[:i]] = kv[i+1:]")
	p.Dedent()
	p.Line("}")
	p.Dedent()
	p.Line("}")
	p.Line("return loadFromMap(m)")
	p.Dedent()
	p.Line("}")
	p.Blank()

	p.Line("func loadFromMap(m map[string]string) (Env, error) {")
	p.Indent()
	p.Line("var e Env")

	for _, f := range g.schema.Fields {
		if err := g.writeFieldLoad(p, f); err != nil {
			return err
		}
	}

	p.Line("return e, nil")
	p.Dedent()
	p.Line("}")
	p.Blank()

	return nil
}

func (g *gen) writeEnumHelper(p *printer.Printer) {
	if !g.hasEnum {
		return
	}

	p.WriteRaw(enumHelperSource)
	p.Blank()
}

func (g *gen) writeExpandHelper(p *printer.Printer) {
	if !g.hasExpand {
		return
	}

	p.WriteRaw(expandHelperSource)
	p.Blank()
}

func (g *gen) writeRegexVars(p *printer.Printer) {
	for _, f := range g.schema.Fields {
		if !f.HasRegex() {
			continue
		}

		p.Linef("var %s = regexp.MustCompile(%q)", g.regexVar(f), f.Regex)
		p.Blank()
	}
}
